# Action 파일 제목
name: Spring Boot Gradle CI/CD

# 어디에 올릴 건지
on:
  push:
    branches: ["main"]
  # 수동으로 Action 실행할 수 있게 해주는 옵션
  workflow_dispatch:

# 진행할 내용 
jobs:
  # build, 배포에 활용되는 환경 잡아주기
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # 파일에 문제가 없는지 체크하는 용도
      - name: Set up JDK 17
        uses: actions/setup-java@v3
      # 자바 버전 세팅
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Copy JAR to Public Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_HOST }} # 환경 변수(바뀔 수 있는 값 - 나중에 설정해줘야함!)
          username: root
          key: ${{ secrets.PUBLIC_SSH_KEY }} # 사설키를 넣어야 함.
          source: |
            build/libs/*SNAPSHOT.jar
          target: /root/app/ # 경로
          
      - name: Copy deploy script to Public Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PUBLIC_HOST }}
          username: root
          key: ${{ secrets.PUBLIC_SSH_KEY }}
          source: |
            deploy_private.sh
          target: /root/app/

# please
      - name: Execute deploy_private.sh on Public Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_HOST }}
          username: root
          key: ${{ secrets.PUBLIC_SSH_KEY }}
          script: |
            chmod +x /root/app/deploy_private.sh
            /root/app/deploy_private.sh
